### ISSUE TITLE
URL does not work 

### ISSUE THREAD

**Issue by lomadi** [bibbox/app-limesurvey#1]
URL does not work
http://ls.demo-new.bibbox.org
does not redirect to 
http://ls.demo-new.bibbox.org/index.php/admin/authentication/sa/login

https://manual.limesurvey.org/Troubleshooting/de

**Comment by lomadi** [comment]
still does not work
http://demo-new.bibbox.org/web/guest/instances
klick on App, this URL appears
http://foss.demo-new.bibbox.org

**Comment by Balfear** [comment]
This should be an issue with changing the domain name of the vm, not a problem with LimeSurvey. Closing for now.
